// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cyhufqbhwryvqdblkiur.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN5aHVmcWJod3J5dnFkYmxraXVyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU3MDAwMjMsImV4cCI6MjA3MTI3NjAyM30.VrVLU2Z3xDxJADWCEyZ79lTf9fjnwajdu2NiYGyU_AU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});